name = "DetectAlpha"
uuid = "2a04ccd2-9adb-4fac-ae12-f23e4991d00f"
authors = ["Brad D"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
